# Generated by Django 4.2.11 on 2024-11-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_answerlikes_answerlike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlike',
            name='like',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='like',
        ),
    ]
