# Generated by Django 4.2.11 on 2024-11-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_answerlike_like_remove_questionlike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='like',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionlike',
            name='like',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1),
            preserve_default=False,
        ),
    ]
