# Generated by Django 4.2.11 on 2024-12-01 18:10

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_answer_author_alter_question_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/home/artem/code/vk-web/web-tech/dz4/AbobaHelp/static/img/avatars')),
        ),
    ]
